name: Run tools

on: [ push, pull_request ]

jobs:
  tools:
    strategy:
      matrix:
        go-version: [ "1.21", "1.22" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run go-licenses
      run: make .licenses GO_VERSION=${{ matrix.go-version }}
    - name: Build manifest-tool
      run: make manifest-list BINS= GO_VERSION=${{ matrix.go-version }}
